(function(){
 const {cfg, root, auth, EMOJIS, esc, clamp, ensureAnon, listenState, listenQuestion, offQuestion} = MTApp;
 const localKey='mt_debate_profile_v2'; let profile=JSON.parse(localStorage.getItem(localKey)||'{}'); if(!profile.emoji) profile.emoji=EMOJIS[Math.floor(Math.random()*EMOJIS.length)]; let state={questionIndex:0,stage:'join'}; let q=null; let currentIndex=null; let side=null; let uid=null;
 const toast=(t)=>document.getElementById('toast').textContent=t;
 function save(){localStorage.setItem(localKey,JSON.stringify(profile));}
 function render(){ if(!q){document.getElementById('mobileStage').textContent='活动尚未初始化，请稍候刷新。'; return;} document.getElementById('choiceA').textContent=q.sideA||'A'; document.getElementById('choiceB').textContent=q.sideB||'B'; document.getElementById('mobileStage').textContent= state.stage==='join'?'请选择你的持方。':state.stage==='debate'?'辩论进行中，可以贡献观点。':state.stage==='paused'?'互动暂时暂停，请关注大屏。':'本题结果展示中，请关注大屏。'; document.getElementById('joinBox').style.display= side?'none':'block'; document.getElementById('badge').style.display= side?'flex':'none'; document.getElementById('commentBox').style.display= side && state.stage==='debate'?'block':'none'; document.getElementById('myEmoji').textContent=profile.emoji; document.getElementById('myName').textContent=profile.nickname||'我'; document.getElementById('mySide').textContent= side ? `已加入：${side==='A'?(q.sideA||'A'):(q.sideB||'B')}`:'未选择'; document.querySelectorAll('.choice').forEach(el=>el.classList.toggle('active', el.dataset.side===profile.side)); }
 async function loadMyParticipant(){ if(!uid) return; const s=await root.child(`questions/${state.questionIndex}/participants/${uid}`).once('value'); const v=s.val(); side=v&&v.side; if(v){ profile.nickname=v.nickname; profile.emoji=v.emoji; profile.side=v.side; save(); } render(); }
 document.querySelectorAll('.choice').forEach(el=>el.onclick=()=>{ profile.side=el.dataset.side; render(); });
 document.getElementById('joinBtn').onclick=async()=>{ await ensureAnon(); uid=auth.currentUser.uid; const nickname=clamp(document.getElementById('nickname').value, cfg.limits.nicknameMax); if(!nickname){toast('请先输入昵称'); return;} if(!profile.side){toast('请选择A或B持方'); return;} profile.nickname=nickname; save(); const data={nickname, emoji:profile.emoji, side:profile.side, uid, joinedAt:firebase.database.ServerValue.TIMESTAMP}; await root.child(`questions/${state.questionIndex}/participants/${uid}`).set(data); side=profile.side; toast('加入成功！请关注大屏。'); render(); };
 document.getElementById('sendBtn').onclick=async()=>{ await ensureAnon(); uid=auth.currentUser.uid; const text=clamp(document.getElementById('comment').value, cfg.limits.commentMax); if(!text){toast('请先输入观点'); return;} if(!side){toast('请先加入阵营'); return;} await root.child(`questions/${state.questionIndex}/comments`).push({text, side, nickname:profile.nickname||'匿名', emoji:profile.emoji, uid, status:'pending', createdAt:firebase.database.ServerValue.TIMESTAMP}); document.getElementById('comment').value=''; toast('提交成功，等待审核上墙。'); };
 auth.onAuthStateChanged(async u=>{ if(u){uid=u.uid; await loadMyParticipant();} }); ensureAnon();
 listenState(st=>{ state=st; if(currentIndex!==st.questionIndex){ if(currentIndex!==null) offQuestion(currentIndex); currentIndex=st.questionIndex; side=null; listenQuestion(currentIndex,qq=>{q=qq; loadMyParticipant(); render();}); } else render(); });
 render();
})();
